# Generated by Django 3.2 on 2021-05-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_type',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
